---
Standards:
  -
    Title: Welcome To Ada
    Description: Resources on Ada as an organization, what we do, and how we do it.
    UID: 10213b4addb0ca7959098f086969d97c
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 97fab403fbc948fcc6a9a2253220487e
        Path: /00-welcome-to-ada/01-wk01-what-is-ada.md
      -
        Type: Lesson
        UID: d9f69c52d660e990ab941ecaced90957
        Path: /00-welcome-to-ada/02-wk01-online-communication-norms.md
      -
        Type: Lesson
        UID: 8eecb85d142ac5ac84c3c2d8ac58e0cb
        Path: /00-welcome-to-ada/03-wk01-learn.md
      -
        Type: Lesson
        UID: 5865d823948e3e2c1a1b427cda05aeac
        Path: /00-welcome-to-ada/04-wk01-slack.md
      -
        Type: Lesson
        UID: a2770c9798f93043e947942f2c34353b
        Path: /00-welcome-to-ada/05-wk01-google-calendar.md
      -
        Type: Lesson
        UID: a82bc49eda1f6a23f982a9ed5c6147df
        Path: /00-welcome-to-ada/06-wk01-ada-worksheets.md
      -
        Type: Lesson
        UID: c687f860e47f121d097b6bf849d614c4
        Path: /00-welcome-to-ada/06-wk01-one-on-ones.md
  -
    Title: Potpourri
    Description: Potpourri
    UID: 13db1562f6ff30eb9b59c1a5499affbd
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 36adde5b697a53e866b091e73ffc5eb2
        Path: /05-potpourri/01-wk01-pseudocode.md
