---
Standards:
  -
    Title: Welcome To Ada
    Description: Resources on Ada as an organization, what we do, and how we do it.
    UID: 10213b4addb0ca7959098f086969d97c
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 97fab403fbc948fcc6a9a2253220487e
        Path: /00-welcome-to-ada/01-wk01-what-is-ada.md
      -
        Type: Lesson
        UID: d9f69c52d660e990ab941ecaced90957
        Path: /00-welcome-to-ada/02-wk01-online-communication-norms.md
      -
        Type: Lesson
        UID: 8eecb85d142ac5ac84c3c2d8ac58e0cb
        Path: /00-welcome-to-ada/03-wk01-learn.md
      -
        Type: Lesson
        UID: 5865d823948e3e2c1a1b427cda05aeac
        Path: /00-welcome-to-ada/04-wk01-slack.md
      -
        Type: Lesson
        UID: a2770c9798f93043e947942f2c34353b
        Path: /00-welcome-to-ada/05-wk01-google-calendar.md
      -
        Type: Lesson
        DefaultVisibility: hidden
        UID: cd5a1f28cba4e4650979d2c009f65691
        Path: /00-welcome-to-ada/06-wk01-one-on-ones-hidden.md
      -
        Type: Lesson
        UID: c687f860e47f121d097b6bf849d614c4
        Path: /00-welcome-to-ada/06-wk01-one-on-ones.md
      -
        Type: Lesson
        UID: eb0e68da-4a5b-4743-a215-a97b70c20739
        Path: /00-welcome-to-ada/07-wk01-study-like-a-programmer.md
      -
        Type: Lesson
        UID: 9a51eac7-e0c7-46ee-8a43-2eb27fca0263
        Path: /00-welcome-to-ada/08-wk01-intro-to-debugging.md
      -
        Type: Lesson
        UID: 596e01dc-936c-4443-820c-d4ebb5ef24a2
        Path: /00-welcome-to-ada/09-wk01-activity-study-techniques.md
      -
        Type: Lesson
        UID: e24f32de-c053-4b5f-a92c-375d6737668a
        Path: /00-welcome-to-ada/10-wk01-debugging-with-rubymine.md
  -
    Title: Roundtable Guides
    Description: Guides to individual roundtables
    UID: 11a4f36cf40d24a975ed0f4e931ef4c1
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: dbaee99a4efbf63e8044ea299054ed66
        Path: /01-roundtable-guides/01-roundtables.md
      -
        Type: Lesson
        UID: c4b53e77-a8c5-4fd5-bd43-a827a01c51c0
        Path: /01-roundtable-guides/02-wk01-roundtable-1.md
      -
        Type: Lesson
        UID: ddede568-91aa-4351-bbd2-1c1df2868998
        Path: /01-roundtable-guides/03-wk02-roundtable-1.md       
      -
        Type: Lesson
        UID: e8651a38-c1f1-4db1-ba39-3322e32f600c
        Path: /01-roundtable-guides/04-wk02-roundtable-2.md  
  -
    Title: Git
    Description: Guides for our favorite version control software!
    UID: a1d4175a-8a14-41c7-95b3-a4e125b401f9
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 27b8aabe-05c1-4839-bbd5-8b182ba98454
        Path: /03-git/01-intro-to-git.md  
  -
    Title: Testing
    Description: Introduction to Test Driven Development
    UID: b95acdc3-901f-4cd8-b25f-91e32909775a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cbee8749-3051-4e31-b9d7-2875c399f2c5
        Path: /02-testing/01-wk03-intro-to-testing.md  
        -
          Type: Lesson
          UID: 8f2b5e0f-9426-40f3-a84c-baab848b41c9
          Path: /02-testing/02-wk03-testing-with-minitest.md       
      -
        Type: Lesson
        UID: bb1307ba-21b0-4b9f-acec-84c3bfb436fd
        Path: /02-testing/03-wk03-testing-exercise.md
  -
    Title: Potpourri
    Description: Includes even more resources on developer skills!
    UID: 13db1562f6ff30eb9b59c1a5499affbd
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 36adde5b697a53e866b091e73ffc5eb2
        Path: /05-potpourri/01-wk01-pseudocode.md
      -
        Type: Lesson
        UID: 565712d4-eafd-4bcc-adc4-57fe6fed4855
        Path: /05-potpourri/02-wk01-exercise-intro-hundred-acre-woods.md
