---
Standards:
  -
    Title: Welcome To Ada
    Description: Resources on Ada as an organization, what we do, and how we do it.
    UID: 10213b4addb0ca7959098f086969d97c
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 97fab403fbc948fcc6a9a2253220487e
        Path: /00-welcome-to-ada/01-wk01-what-is-ada.md
      -
        Type: Lesson
        UID: d9f69c52d660e990ab941ecaced90957
        Path: /00-welcome-to-ada/02-wk01-online-communication-norms.md
      -
        Type: Lesson
        UID: 8eecb85d142ac5ac84c3c2d8ac58e0cb
        Path: /00-welcome-to-ada/03-wk01-learn.md
      -
        Type: Lesson
        UID: 418a54c4-d07c-46d5-b05c-09764399b81d
        Path: /00-welcome-to-ada/online-meeting-rooms.md
      -
        Type: Lesson
        UID: 5865d823948e3e2c1a1b427cda05aeac
        Path: /00-welcome-to-ada/04-wk01-slack.md
      -
        Type: Lesson
        UID: a2770c9798f93043e947942f2c34353b
        Path: /00-welcome-to-ada/05-wk01-google-calendar.md
      -
        Type: Lesson
        UID: 0a01b55a-9fc3-4e44-983f-0fe1932e68cb
        Path: /00-welcome-to-ada/06-wk01-attendance.md
      -
        Type: Lesson
        UID: 7485be11-9447-4d64-b197-1fd7ded86b89
        Path: /00-welcome-to-ada/07-wk01-project-feedback.md
      -
        Type: Lesson
        DefaultVisibility: hidden
        UID: cd5a1f28cba4e4650979d2c009f65691
        Path: /00-welcome-to-ada/08-wk01-one-on-ones-hidden.md
      -
        Type: Lesson
        UID: c687f860e47f121d097b6bf849d614c4
        Path: /00-welcome-to-ada/08-wk01-one-on-ones.md
      -
        Type: Lesson
        UID: eb0e68da-4a5b-4743-a215-a97b70c20739
        Path: /00-welcome-to-ada/09-wk01-study-like-a-programmer.md
      -
        Type: Lesson
        UID: 9a51eac7-e0c7-46ee-8a43-2eb27fca0263
        Path: /00-welcome-to-ada/10-wk01-intro-to-debugging.md
      -
        Type: Lesson
        UID: 596e01dc-936c-4443-820c-d4ebb5ef24a2
        Path: /00-welcome-to-ada/11-wk01-activity-study-techniques.md
      -
        Type: Lesson
        UID: e24f32de-c053-4b5f-a92c-375d6737668a
        Path: /00-welcome-to-ada/12-wk01-debugging-with-rubymine.md
      -
        Type: Lesson
        UID: 00032272-e60a-4403-80ef-242b2e1591b4
        Path: /00-welcome-to-ada/wk-02-what-is-a-retro.md
      
  -
    Title: Unit 1 Roundtable Guides
    Description: Guides to individual roundtables (Ruby and HTML/CSS)
    UID: 11a4f36cf40d24a975ed0f4e931ef4c1
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: dbaee99a4efbf63e8044ea299054ed66
        Path: /01-unit1-roundtable-guides/01-roundtables.md
      -
        Type: Lesson
        UID: c4b53e77-a8c5-4fd5-bd43-a827a01c51c0
        Path: /01-unit1-roundtable-guides/02-wk01-roundtable-1.md
      -
        Type: Lesson
        UID: ddede568-91aa-4351-bbd2-1c1df2868998
        Path: /01-unit1-roundtable-guides/03-wk02-roundtable-1.md
      -
        Type: Lesson
        UID: cfdda273-3ad8-4c46-ba2c-0747ce373060
        Path: /01-unit1-roundtable-guides/04-wk03-tdd-exercise-roundtable.md
      -
        Type: Lesson
        UID: 45ee5257-c1b9-4a1d-b038-78b17d30dd82
        Path: /01-unit1-roundtable-guides/05-wk04-1-classes.md
      -
        Type: Lesson
        UID: fa25e288-bec7-4a64-842f-3b0a56e67e02
        Path: /01-unit1-roundtable-guides/06-wk04-2-object-oriented-design.md
      -
        Type: Lesson
        UID: b793a3c2-6ae2-48bf-a482-4639b330d322
        Path: /01-unit1-roundtable-guides/07-wk05-grocery-store.md
      -
        Type: Lesson
        UID: a8c68198-154c-43f4-990b-927c2e0ca391
        Path: /01-unit1-roundtable-guides/08-wk05-tdd-oop-before-let.md
      -
        Type: Lesson
        UID: 7748b481-2bc6-4ddf-b36e-0e30fb31668f
        Path: /01-unit1-roundtable-guides/09-wk06-references-and-values.md
      -
        Type: Lesson
        UID: d631fd49-41d5-435a-adce-a6cedf5c5672
        Path: /01-unit1-roundtable-guides/10-wk06-oorideshare-review.md
      -
        Type: Lesson
        UID: 3ccb24af-023c-4dee-b1c1-e7b0560c1663
        Path: /01-unit1-roundtable-guides/11-wk06-apis.md
      -
        Type: Lesson
        UID: d06a30c6-b653-452f-93ed-6bed4594127f
        Path: /01-unit1-roundtable-guides/12-wk07-book-review-site.md
      -
        Type: Lesson
        UID: c9e29323-bef4-44bb-ad4c-494b633ca22a
        Path: /01-unit1-roundtable-guides/13-wk07-open-ended-discussion.md
      -
        Type: Lesson
        UID: 9350205e-8487-4a24-89bd-e37ec1bee012
        Path: /01-unit1-roundtable-guides/project-reviews-instructor-guide-hidden.md
  -
    Title: Unit 2 Roundtable Guides
    Description: Guides to individual roundtables (Rails)
    UID: aeb253f6ade3-4a828c193de7625a6a90
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8ec89c68-8192-4935-b5bc-74151b14a8d6
        Path: /02-unit2-roundtable-guides/01-wk09-rails-day-1.md
      -
        Type: Lesson
        UID: d5695b32-7d8a-4d01-9728-87cba344b870
        Path: /02-unit2-roundtable-guides/02-wk09-tasklist-and-books-destroy.md
      -
        Type: Lesson
        UID: 1aa96770-9afe-47d6-b8fa-8db0cf355e86
        Path: /02-unit2-roundtable-guides/03-wk10-tasklist-review.md
      -
        Type: Lesson
        UID: 1589510a-ecd4-4aa7-8010-7b6da8097dd4
        Path: /02-unit2-roundtable-guides/04-wk10-strong-params-branching.md
      -
        Type: Lesson
        UID: 6b707566-df65-4d5f-94f9-77ec39ebb661
        Path: /02-unit2-roundtable-guides/05-wk10-relationships-validations.md
      -
        Type: Lesson
        UID: 71ff88d5-7d63-4c3c-8f7a-fdb0e8f09b4c
        Path: /02-unit2-roundtable-guides/06-wk11-roman-numerals-and-media-ranker.md
      -
        Type: Lesson
        UID: d72af5b7-c2d7-4cb3-adfb-524139585331
        Path: /02-unit2-roundtable-guides/07-wk11-test-db-flash-and-media-ranker.md
      -
        Type: Lesson
        UID: 4e8fdcae-546b-40a0-b424-20772b371765
        Path: /02-unit2-roundtable-guides/08-wk11-session.md
      -
        Type: Lesson
        UID: 7268dae2-cdb1-4c11-a36e-80cec22ac096
        Path: /02-unit2-roundtable-guides/09-wk14-rails-api.md
  -
    Title: Unit 3 Roundtable Guides
    Description: Guides to individual roundtables (Javascript/React)
    UID: df3945dc-6966-4f2e-b2d9-845f5eeb5d6d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: fe1796fd-25fb-4927-84b8-0c36311d6058
        Path: /03-unit3-roundtable-guides/01-wk15-intro-to-js.md
      -
        Type: Lesson
        UID: 49f85bf7-0baf-41a0-9174-1768e51f6002
        Path: /03-unit3-roundtable-guides/02-wk15-js-functions.md 
      -
        Type: Lesson
        UID: 17e15db3-4934-45ec-ad3b-471ee670433e
        Path: /03-unit3-roundtable-guides/03-wk15-testing-adagrams.md 
      -
        Type: Lesson
        UID: 2c5e06c5-3a0a-46c7-99b2-2ad0b83af6a5
        Path: /03-unit3-roundtable-guides/04-wk16-axios.md 
      -
        Type: Lesson
        UID: 6385d5f4-d59c-4c85-b957-75142cf76ba5
        Path: /03-unit3-roundtable-guides/05-wk16-react-intro.md  
      -
        Type: Lesson
        UID: c0e71848-c028-48c7-a07b-d4e06e13deb4
        Path: /03-unit3-roundtable-guides/06-wk17-react2.md 
      -
        Type: Lesson
        UID: 691b8aea-48bd-48d8-b9c3-da13955068e4
        Path: /03-unit3-roundtable-guides/07-wk17-tic-tac-toe.md 
      -
        Type: Lesson
        UID: 96caee4d-bb67-4799-970f-ab5840b33024
        Path: /03-unit3-roundtable-guides/08-wk18-forms.md 
      -
        Type: Lesson
        UID: 99f9a567-60d9-4a7c-8c93-c725bbe86884
        Path: /03-unit3-roundtable-guides/09-wk18-useeffect.md 
      
  -
    Title: Git
    Description: Guides for our favorite version control software!
    UID: a1d4175a-8a14-41c7-95b3-a4e125b401f9
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 27b8aabe-05c1-4839-bbd5-8b182ba98454
        Path: /04-git/intro-to-git.md 
      -
        Type: Lesson
        UID: 5b9cc8ad-4ae6-4e6d-885a-234a813e1f60
        Path: /04-git/git-push.md            
      -
        Type: Lesson
        UID: 0de0c84b-4480-440a-954e-566d776a321a
        Path: /04-git/gitignore.md
      -
        Type: Lesson
        UID: bdb52de8-4a40-4263-82c8-f77627e8f39e
        Path: /04-git/git-pull-activity.md
      -
        Type: Lesson
        UID: 6055fea3-dea1-45f6-984b-05a9f119f5b6
        Path: /04-git/branches.md
      -
        Type: Lesson
        UID: fa30fd02-5e49-41af-8248-3f81144da34b
        Path: /04-git/git-merge-conflicts.md
      -
        Type: Lesson
        UID: 477ad971-0328-42fc-83d7-4e3253b4fb20
        Path: /04-git/pull-requests.md
      - 
        Type: Lesson
        UID: 15a93289-1666-470d-a785-080b8d492018
        Path: /04-git/merge-conflict-remote.md
  -
    Title: Testing
    Description: Introduction to Test Driven Development
    UID: b95acdc3-901f-4cd8-b25f-91e32909775a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cbee8749-3051-4e31-b9d7-2875c399f2c5
        Path: /05-testing/01-wk03-intro-to-testing.md  
      -
        Type: Lesson
        UID: 8f2b5e0f-9426-40f3-a84c-baab848b41c9
        Path: /05-testing/02-wk03-testing-with-minitest.md       
      -
        Type: Lesson
        UID: bb1307ba-21b0-4b9f-acec-84c3bfb436fd
        Path: /05-testing/03-wk03-testing-exercise.md
      -
        Type: Lesson
        UID: 439218bc-8c65-4720-b939-822d282a7058
        Path: /05-testing/04-wk05-testing-with-before-and-let.md
      -
        Type: Lesson
        UID: 239cc796-7d67-4fd2-b8e2-13b8010901a6
        Path: /05-testing/tdd-in-oop-exercise.md
      -
        Type: Lesson
        UID: 7797caba-b44d-4423-9fa3-87c6dddd596e
        Path: /05-testing/api-testing-vcr.md
      -
        Type: Lesson
        UID: 52f0f06b-8d67-4643-9e5d-88ac1c4a2ccc
        Path: /05-testing/code-coverage-and-simplecov.md
      -
        Type: Lesson
        UID: 5ca23f76-467d-44c9-8c7d-41b0b8622147
        Path: /05-testing/testing-with-guard.md

  -
    Title: Potpourri
    Description: Includes even more resources on developer skills!
    UID: 13db1562f6ff30eb9b59c1a5499affbd
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 36adde5b697a53e866b091e73ffc5eb2
        Path: /06-potpourri/01-wk01-pseudocode.md
      -
        Type: Lesson
        UID: 565712d4-eafd-4bcc-adc4-57fe6fed4855
        Path: /06-potpourri/02-wk01-exercise-intro-hundred-acre-woods.md
      -
        Type: Lesson
        UID: a487c50d-feb5-45de-88d3-8c2075c9baf9
        Path: /06-potpourri/03-programming-techniques.md
      -
        Type: Lesson
        UID: d9a06edd-5e6b-43fe-923d-6687494db3d3
        Path: /06-potpourri/04-pair-feedback-and-code-reviews.md
      -
        Type: Lesson
        UID: 2ee2d4d1-7547-4264-aab4-68484cbd7ae4
        Path: /06-potpourri/05-intro-to-regex.md
      -
        Type: Lesson
        UID: 164fb964-84f7-4441-aa15-b7a492cc0749
        Path: /06-potpourri/04-wk-05-request-response-cycles.md
      -
        Type: Lesson
        UID: a2c99690-f554-454c-828b-a97a0da27d59
        Path: /06-potpourri/exercism.md
      -
        Type: Lesson
        UID: 1d6d6c36-2f6e-4767-a61e-afb069170360
        Path: /06-potpourri/queries-and-commands.md
      -
        Type: Lesson
        UID: 79ded5d9-c4a4-445d-b1d0-75f2712a1566
        Path: /06-potpourri/intro-to-agile.md
      -
        Type: Lesson
        UID: 398dca78-45b7-4f63-88fc-665a5be9e02c
        Path: /06-potpourri/user-stories.md
      - 
        Type: Lesson
        UID: ca1eefcb-5030-4739-81d5-f05d14696f6e
        Path: /06-potpourri/intro-to-wireframes.md
      -
        Type: Lesson
        UID: ab437a21-a434-4d53-a0bd-88aa380e8c80
        Path: /06-potpourri/continuous-integration.md
  -
    Title: Capstone Overview
    Description: Capstone Project Overview
    UID: cd1689b5-727f-4858-b0bd-618429fc1010
    SuccessCriteria:
      - success criteria
    ContentFiles:
      - 
        Type: Lesson
        UID: 187a7483-8ab4-4f1b-9bd6-c26b293a9cd3
        Path: /capstone-overview/intro.md
      -
        Type: Lesson
        UID: 1a108df1-0639-4635-90d3-7c1eb7d3477c
        Path: /capstone-overview/brainstorming.md
      -
        Type: Lesson
        UID: 9b5449fa-75f3-4526-8818-8eafec55d6a6
        Path: /capstone-overview/tech-stacks.md
      -
        Type: Lesson
        UID: 89a228fa-9411-4077-8298-98d523eeff7e
        Path: /capstone-overview/tech-stack-examples.md
      -
        Type: Lesson
        UID: 003099a8-3ede-4d8a-9c25-5439153792af
        Path: /capstone-overview/tech-stack-research.md
      -
        Type: Lesson
        UID: a7d96954-6206-492d-8596-ab29c0830495
        Path: /capstone-overview/advice.md
      -
        Type: Lesson
        UID: d4a2446e-e930-464e-afd2-f8ef6267ba18
        Path: /capstone-overview/groups.md
      -
        Type: Lesson
        UID: 19e95ccd-a90c-457b-b93e-f19635ff52db
        Path: /capstone-overview/tutorial-sites.md
      -
        Type: Checkpoint
        UID: 9019c352-972d-48af-83ac-36286ff8cc2d
        Path: /capstone-overview/capstone-concept.checkpoint.md
      -
        Type: Lesson
        UID: 82a52be6-222a-4148-a204-879f009e285e
        Path: /capstone-overview/capstone-proposal.md
      -
        Type: Lesson
        UID: ed75ec59-7cc1-4839-97ac-56ee9c3c98db
        Path: /capstone-overview/capstone-presentation.md
      -
        Type: Lesson
        UID: 38ddf7af-36b7-43a9-b8dc-bc6dad2177fc
        Path: /capstone-overview/reflections.md