---
Standards:
  -
    Title: Welcome To Ada
    Description: Resources on Ada as an organization, what we do, and how we do it.
    UID: 10213b4addb0ca7959098f086969d97c
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 97fab403fbc948fcc6a9a2253220487e
        Path: /00-welcome-to-ada/01-wk01-what-is-ada.md
      -
        Type: Lesson
        UID: d9f69c52d660e990ab941ecaced90957
        Path: /00-welcome-to-ada/02-wk01-online-communication-norms.md
      -
        Type: Lesson
        UID: 8eecb85d142ac5ac84c3c2d8ac58e0cb
        Path: /00-welcome-to-ada/03-wk01-learn.md
      -
        Type: Lesson
        UID: 418a54c4-d07c-46d5-b05c-09764399b81d
        Path: /00-welcome-to-ada/online-meeting-rooms.md
      -
        Type: Lesson
        UID: 5865d823948e3e2c1a1b427cda05aeac
        Path: /00-welcome-to-ada/04-wk01-slack.md
      -
        Type: Lesson
        UID: a2770c9798f93043e947942f2c34353b
        Path: /00-welcome-to-ada/05-wk01-google-calendar.md
      -
        Type: Lesson
        UID: 0a01b55a-9fc3-4e44-983f-0fe1932e68cb
        Path: /00-welcome-to-ada/06-wk01-attendance.md
      -
        Type: Lesson
        UID: 7485be11-9447-4d64-b197-1fd7ded86b89
        Path: /00-welcome-to-ada/07-wk01-project-feedback.md
      -
        Type: Lesson
        DefaultVisibility: hidden
        UID: cd5a1f28cba4e4650979d2c009f65691
        Path: /00-welcome-to-ada/08-wk01-one-on-ones-hidden.md
      -
        Type: Lesson
        UID: c687f860e47f121d097b6bf849d614c4
        Path: /00-welcome-to-ada/08-wk01-one-on-ones.md
      -
        Type: Lesson
        UID: eb0e68da-4a5b-4743-a215-a97b70c20739
        Path: /00-welcome-to-ada/09-wk01-study-like-a-programmer.md
      -
        Type: Lesson
        UID: 9a51eac7-e0c7-46ee-8a43-2eb27fca0263
        Path: /00-welcome-to-ada/10-wk01-intro-to-debugging.md
      -
        Type: Lesson
        UID: 596e01dc-936c-4443-820c-d4ebb5ef24a2
        Path: /00-welcome-to-ada/11-wk01-activity-study-techniques.md
      -
        Type: Lesson
        UID: e24f32de-c053-4b5f-a92c-375d6737668a
        Path: /00-welcome-to-ada/12-wk01-debugging-with-rubymine.md
      -
        Type: Lesson
        UID: 00032272-e60a-4403-80ef-242b2e1591b4
        Path: /00-welcome-to-ada/wk-02-what-is-a-retro.md
      
  -
    Title: Unit 1 Roundtable Guides
    Description: Guides to individual roundtables (Ruby and HTML/CSS)
    UID: 11a4f36cf40d24a975ed0f4e931ef4c1
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: dbaee99a4efbf63e8044ea299054ed66
        Path: /01-unit1-roundtable-guides/01-roundtables.md
      -
        Type: Lesson
        UID: c4b53e77-a8c5-4fd5-bd43-a827a01c51c0
        Path: /01-unit1-roundtable-guides/02-wk01-roundtable-1.md
      -
        Type: Lesson
        UID: ddede568-91aa-4351-bbd2-1c1df2868998
        Path: /01-unit1-roundtable-guides/03-wk02-roundtable-1.md
      -
        Type: Lesson
        UID: cfdda273-3ad8-4c46-ba2c-0747ce373060
        Path: /01-unit1-roundtable-guides/04-wk03-tdd-exercise-roundtable.md
      -
        Type: Lesson
        UID: 45ee5257-c1b9-4a1d-b038-78b17d30dd82
        Path: /01-unit1-roundtable-guides/05-wk04-1-classes.md
      -
        Type: Lesson
        UID: fa25e288-bec7-4a64-842f-3b0a56e67e02
        Path: /01-unit1-roundtable-guides/06-wk04-2-object-oriented-design.md
      -
        Type: Lesson
        UID: b793a3c2-6ae2-48bf-a482-4639b330d322
        Path: /01-unit1-roundtable-guides/07-wk05-grocery-store.md
      -
        Type: Lesson
        UID: a8c68198-154c-43f4-990b-927c2e0ca391
        Path: /01-unit1-roundtable-guides/08-wk05-tdd-oop-before-let.md
      -
        Type: Lesson
        UID: 7748b481-2bc6-4ddf-b36e-0e30fb31668f
        Path: /01-unit1-roundtable-guides/09-wk06-references-and-values.md
      -
        Type: Lesson
        UID: d631fd49-41d5-435a-adce-a6cedf5c5672
        Path: /01-unit1-roundtable-guides/10-wk06-oorideshare-review.md
      -
        Type: Lesson
        UID: 3ccb24af-023c-4dee-b1c1-e7b0560c1663
        Path: /01-unit1-roundtable-guides/11-wk06-apis.md
      -
        Type: Lesson
        UID: d06a30c6-b653-452f-93ed-6bed4594127f
        Path: /01-unit1-roundtable-guides/12-wk07-book-review-site.md
      -
        Type: Lesson
        UID: c9e29323-bef4-44bb-ad4c-494b633ca22a
        Path: /01-unit1-roundtable-guides/13-wk07-open-ended-discussion.md
      -
        Type: Lesson
        UID: 9350205e-8487-4a24-89bd-e37ec1bee012
        Path: /01-unit1-roundtable-guides/project-reviews-instructor-guide-hidden.md
  -
    Title: Git
    Description: Guides for our favorite version control software!
    UID: a1d4175a-8a14-41c7-95b3-a4e125b401f9
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 27b8aabe-05c1-4839-bbd5-8b182ba98454
        Path: /03-git/intro-to-git.md 
      -
        Type: Lesson
        UID: 5b9cc8ad-4ae6-4e6d-885a-234a813e1f60
        Path: /03-git/git-push.md            
      -
        Type: Lesson
        UID: 0de0c84b-4480-440a-954e-566d776a321a
        Path: /03-git/gitignore.md
      -
        Type: Lesson
        UID: bdb52de8-4a40-4263-82c8-f77627e8f39e
        Path: /03-git/git-pull-activity.md        
  -
    Title: Testing
    Description: Introduction to Test Driven Development
    UID: b95acdc3-901f-4cd8-b25f-91e32909775a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: cbee8749-3051-4e31-b9d7-2875c399f2c5
        Path: /02-testing/01-wk03-intro-to-testing.md  
      -
        Type: Lesson
        UID: 8f2b5e0f-9426-40f3-a84c-baab848b41c9
        Path: /02-testing/02-wk03-testing-with-minitest.md       
      -
        Type: Lesson
        UID: bb1307ba-21b0-4b9f-acec-84c3bfb436fd
        Path: /02-testing/03-wk03-testing-exercise.md
      -
        Type: Lesson
        UID: 439218bc-8c65-4720-b939-822d282a7058
        Path: /02-testing/04-wk05-testing-with-before-and-let.md
      -
        Type: Lesson
        UID: 239cc796-7d67-4fd2-b8e2-13b8010901a6
        Path: /02-testing/tdd-in-oop-exercise.md
      -
        Type: Lesson
        UID: 7797caba-b44d-4423-9fa3-87c6dddd596e
        Path: /02-testing/api-testing-vcr.md
      -
        Type: Lesson
        UID: 52f0f06b-8d67-4643-9e5d-88ac1c4a2ccc
        Path: /02-testing/code-coverage-and-simplecov.md
      -
        Type: Lesson
        UID: 5ca23f76-467d-44c9-8c7d-41b0b8622147
        Path: /02-testing/testing-with-guard.md

  -
    Title: Potpourri
    Description: Includes even more resources on developer skills!
    UID: 13db1562f6ff30eb9b59c1a5499affbd
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 36adde5b697a53e866b091e73ffc5eb2
        Path: /05-potpourri/01-wk01-pseudocode.md
      -
        Type: Lesson
        UID: 565712d4-eafd-4bcc-adc4-57fe6fed4855
        Path: /05-potpourri/02-wk01-exercise-intro-hundred-acre-woods.md
      -
        Type: Lesson
        UID: a487c50d-feb5-45de-88d3-8c2075c9baf9
        Path: /05-potpourri/03-programming-techniques.md
      -
        Type: Lesson
        UID: d9a06edd-5e6b-43fe-923d-6687494db3d3
        Path: /05-potpourri/04-pair-feedback-and-code-reviews.md
      -
        Type: Lesson
        UID: 2ee2d4d1-7547-4264-aab4-68484cbd7ae4
        Path: /05-potpourri/05-intro-to-regex.md
      -
        Type: Lesson
        UID: 164fb964-84f7-4441-aa15-b7a492cc0749
        Path: /05-potpourri/04-wk-05-request-response-cycles.md
      -
        Type: Lesson
        UID: a2c99690-f554-454c-828b-a97a0da27d59
        Path: /05-potpourri/exercism.md
      -
        Type: Lesson
        UID: 1d6d6c36-2f6e-4767-a61e-afb069170360
        Path: /05-potpourri/queries-and-commands.md
  
